In [2]:
import tensorflow as tf

In [3]:
tf.executing_eagerly()

True

In [4]:
x=[[2.]]
m=tf.matmul(x,x)
print(m)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [5]:
a=tf.constant([[1,2],[3,4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
b=tf.add(a,1)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [7]:
a*b


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [8]:
import numpy as np

In [9]:
c=np.multiply(a,b)
c

array([[ 2,  6],
       [12, 20]])

In [10]:
a.numpy()

array([[1, 2],
       [3, 4]])