# Array

In [2]:
import numpy as np

In [8]:
x=[1,2,3,4,5]
arr1=np.array(x)
print(arr1)
print(type(arr1))
print(arr1.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
l=[]
for i in range(1,5):
    imt_1=int(input('Enter :'))
    l.append(imt_1)
print(np.array(l))

Enter :12
Enter :432
Enter :23
Enter :33
[ 12 432  23  33]


In [11]:
l1=[[12,32,44,32,43,3],[23,23,23,4,55,5]]
arr2=np.array(l1)
print(x)
print(x.ndim)

[[12 32 44 32 43  3]
 [23 23 23  4 55  5]]
2


In [14]:
l2=[[[12,332,434,55],[132,34,55,54],[12,43,55,66]]]
arr3=np.array(l2)
print(arr3)
print(arr3.ndim)

[[[ 12 332 434  55]
  [132  34  55  54]
  [ 12  43  55  66]]]
3


In [16]:
arrn=np.array([1,2,3,4],ndmin=10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros

In [3]:
import numpy as np
arr_zero=np.zeros(4)
arr_zero1=np.zeros((3,4))
print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [6]:
import numpy as np
arr_one=np.ones(4)
arr_one1=np.ones((3,4))
print(arr_one)
print()
print(arr_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [7]:
arr_empty=np.empty(4)
print(arr_empty)

[1. 1. 1. 1.]


# Range

In [8]:
arr_rn=np.arange(4)
print(arr_rn)

[0 1 2 3]


# Diagnol

In [11]:
arr_diagnol=np.eye(3)
print(arr_diagnol)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arr_diagnol=np.eye(3,4)
print(arr_diagnol)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# linespace

In [15]:
arr_linespace=np.linspace(0,20,num=5)
print(arr_linespace)

[ 0.  5. 10. 15. 20.]


# Random

# rand()

In [17]:
arr_random=np.random.rand(4)
print(arr_random)

[0.79719223 0.04318134 0.25904618 0.51251966]


In [20]:
arr_random1=np.random.rand(3,4)
print(arr_random1)

[[0.93174479 0.49579994 0.82487096 0.6879454 ]
 [0.10944298 0.220791   0.08765751 0.62527337]
 [0.42605126 0.67932887 0.13683181 0.85777326]]


# randn()

In [21]:
arr_randomn=np.random.randn(5)
print(arr_randomn)

[-1.62576976 -1.06226218  0.71122524  0.65153889 -0.65947821]


In [22]:
arr_randomn1=np.random.randn(3,4)
print(arr_randomn1)

[[ 0.31879194  2.26795312  0.48175195 -0.42431919]
 [-1.22392758  1.79333808 -2.10609257 -0.54596663]
 [ 1.63004119  0.65257164  0.18684427 -0.56834521]]


# randf()

In [24]:
arr_randomf=np.random.ranf(5)
print(arr_randomf)

[0.20880221 0.30184735 0.75789204 0.21895584 0.13711741]


# randint()

In [26]:
arr_randint=np.random.randint(5,20,5)
print(arr_randint)

[11  7 12 10 12]


# Data Types

In [28]:
arr=np.array([1,2,3,4,12,32,55])
print('Data Type : ',arr.dtype)

Data Type :  int32


In [29]:
arr=np.array([1.4,2.0,3.3,4.6,12.7,32.8,55.4])
print('Data Type : ',arr.dtype)

Data Type :  float64


In [30]:
arr=np.array(['A','B','C','D'])
print('Data Type : ',arr.dtype)

Data Type :  <U1


In [33]:
arr=np.array(['A','B','C','D',1,2,3])
print('Data Type : ',arr.dtype)

Data Type :  <U11


In [36]:
x=np.array([1,2,3,4,5])
print('Data Types :',x.dtype)

Data Types : int32


In [37]:
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x)
print('Data Types :',x.dtype)

[1 2 3 4 5]
Data Types : int8


In [38]:
x1=np.array([1,2,3,4,5],dtype='f')
print(x1)
print('Data Types :',x1.dtype)

[1. 2. 3. 4. 5.]
Data Types : float32


In [42]:
x1=np.array([1,2,3,4,5])
new=np.float32(x1)
new1=np.int_(new)
print(x1)
print('Data Types :',x1.dtype)
print('Data Type : ',new.dtype)
print(new)
print(new1)

[1 2 3 4 5]
Data Types : int32
Data Type :  float32
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [43]:
x1=np.array([1,2,3,4,5])
neww=x1.astype(float)
print(neww)

[1. 2. 3. 4. 5.]


# Arithmetic Operation

In [44]:
var=np.array([1,2,3,4])
varAdd=var+3
print(varAdd)

[4 5 6 7]


In [45]:
varSub=var-1
print(varSub)

[0 1 2 3]


In [47]:
varMultiply=var*2
print(varMultiply)

[2 4 6 8]


In [48]:
varDivision=var/2
print(varDivision)

[0.5 1.  1.5 2. ]


In [49]:
varModulus=var%2
print(varModulus)

[1 0 1 0]


In [50]:
var1=[1,2,3,4]
var2=[1,2,3,4]
varr=np.add(var1,var2)
print(varr)

[2 4 6 8]


# 2D Array

In [52]:
var2d=np.array([[1,2,3,4],[1,2,3,4]])
var2d1=np.array([[1,2,3,4],[1,2,3,4]])
var2dadd=np.add(var2d,var2d1)
print(var2dadd)

[[2 4 6 8]
 [2 4 6 8]]


# Arithmetic Functions

In [58]:
varmin=np.array([1,2,3,4,2])
minvalue=np.min(varmin)
maxvalue=np.max(varmin)
print('Maximum Value : ',maxvalue,' Minimum value : ',minvalue)
print('Index Number Min and Max :',np.argmin(varmin),':',np.argmax(varmin))

Maximum Value :  4  Minimum value :  1
Index Number Min and Max : 0 : 3


In [64]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
print('minimum value column :',np.min(var1,axis=0))

minimum value column : [1 2 3 4]


In [63]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
print('minimum value row :',np.min(var1,axis=1))

minimum value row : [1 5]


In [66]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
print('maximum value column :',np.max(var1,axis=0))

maximum value column : [5 6 7 8]


In [67]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
print('maximum value row :',np.max(var1,axis=1))

maximum value row : [4 8]


# sqrt()

In [68]:
print('Square root :',np.sqrt(var))

Square root : [1.         1.41421356 1.73205081 2.        ]


In [69]:
var2=np.array([1,2,3])
print('sin : ',np.sin(var2))

sin :  [0.84147098 0.90929743 0.14112001]


In [70]:
var2=np.array([1,2,3])
print('cos :',np.cos(var2))

cos : [ 0.54030231 -0.41614684 -0.9899925 ]


In [71]:
var2=np.array([1,2,3])
print('cumsum : ',np.cumsum(var2))

cumsum :  [1 3 6]


# shape & Reshaping

In [3]:
import numpy as np
var=np.array([[1,2,3,4,5],[6,7,8,9,20]])
print(var)
print()
print(var.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 20]]

(2, 5)


In [6]:
var1=np.array([1,2,3,4,5,6],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4 5 6]]]]
4
(1, 1, 1, 6)


# Reshaping

In [14]:
var2=np.array([1,2,3,4,5,6])
print(var2)
print()
x=var2.reshape(3,1,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]

[[[1 2]]

 [[3 4]]

 [[5 6]]]
3


# Broadcasting

# var1=np.array([1,2,3,4])
var2=np.array([6,7,8,9])
print(var1+var2)


# Indexing

# 1D

In [18]:
var=np.array([1,2,3,4,5])
print(var[1])
print()
print(var[-1])

2

5


# 2D

In [24]:
var2=np.array([[1,2,3,4],[6,7,8,9]])
print(var2)
print()
print(var2.ndim)
print()
print(var2[0,3])
print()
print(var2[1,0])

[[1 2 3 4]
 [6 7 8 9]]

2

4

6


# 3D

In [26]:
var3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(var3)
print()
print(var3.ndim)
print()
print(var3[0,1,1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

3

5


# Slicing

In [33]:
va=np.array([1,2,3,4,5,6])
print(va[1:3])
print(va[3:-1])
print(va[1:-1:2])
print(va[2:])
print(va[:-2])
print(va[:5])
print(va[-2:])

[2 3]
[4 5]
[2 4]
[3 4 5 6]
[1 2 3 4]
[1 2 3 4 5]
[5 6]


In [37]:
va1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(va1.ndim)
print(va1[1,0:2])

2
[4 5]


# Iterating Numpy Arrays

In [38]:
va=np.array([1,2,3,4,5,56,6,7])
print(va)
print()
for i in va:
    print(i)

[ 1  2  3  4  5 56  6  7]

1
2
3
4
5
56
6
7


In [46]:
va2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(va2)
print()
for x in va2:
    for j in x:
        print(j,end='')
    print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

12345
678910


In [49]:
va3=np.array([[[1,2,3],[4,5,6]]])
print(va3)
print()
for x in va3:
    for y in x:
        for z in y:
            print(z,end="")

[[[1 2 3]
  [4 5 6]]]

123456

In [50]:
va3=np.array([[[1,2,3],[4,5,6]]])
for i in np.nditer(va3):
    print(i)

1
2
3
4
5
6


In [55]:
va3=np.array([[[1,2,3],[4,5,6]]])
for i in np.nditer(va3):
    print(i)

1
2
3
4
5
6


In [56]:
va3=np.array([[[1,2,3],[4,5,6]]])
for i,d in np.ndenumerate(va3):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6


# Copy Vs View

In [59]:
var=np.array([1,2,3,4,5])
co=var.copy()
var[3]=40
print(var)
print()
print(co)

[ 1  2  3 40  5]

[1 2 3 4 5]


In [60]:
va1=np.array([5,6,7,8,9])
va2=va1.view()
va1[3]=50
print(va1)
print()
print(va2)

[ 5  6  7 50  9]

[ 5  6  7 50  9]


# Join array

In [63]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
arr=np.concatenate((x,y))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [66]:
x1=np.array([[1,2],[3,4]])
y1=np.array([[5,6],[7,8]])
aarnew=np.concatenate((x1,y1),axis=1)
print(aarnew)

[[1 2 5 6]
 [3 4 7 8]]


In [68]:
x_1=np.array([[1,2],[3,4]])
y_1=np.array([[5,6],[7,8]])
aar_new=np.stack((x_1,y_1),axis=1)
arr1=np.hstack((x_1,y_1))#row
arr2=np.vstack((x_1,y_1))#col
arr3=np.dstack((x_1,y_1))#height
print(aar_new)
print()
print(arr1)
print()
print(arr2)
print()
print(arr3)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# Split Array

In [73]:
arrs=np.array([1,2,3,4,5,6,7,8,9])
print(arrs)
ar=np.array_split(arrs,3)
print(type(ar))
print(ar[0])

[1 2 3 4 5 6 7 8 9]
<class 'list'>
[1 2 3]


In [75]:
v1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(v1)
arr1=np.array_split(v1,4,axis=1)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]


# Numpy Arrays Functions

# search

In [80]:
arr_search=np.array([1,2,3,4,5,6,7,8,9,10,2,134,1,3,2,13,2])
x=np.where(arr_search==2)
print(x)

(array([ 1, 10, 14, 16], dtype=int64),)


In [81]:
arr_search=np.array([1,2,3,4,5,6,7,8,9,10,2,134,1,3,2,13,2])
x=np.where((arr_search%2)==0)
print(x)

(array([ 1,  3,  5,  7,  9, 10, 11, 14, 16], dtype=int64),)


In [82]:
arr_search=np.array([1,2,3,4,5,6,7,8,9,10,2,134,1,3,2,13,2])
x1=np.searchsorted(arr_search,5)
print(x1)

4
